import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css";
import { Header } from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <div className="min-h-screen flex items-center justify-center bg-zinc-50 font-sans dark:bg-black p-4">
            <div className="      
              w-full max-w-6xl 
              bg-white dark:bg-neutral-950 
              border border-neutral-200 dark:border-neutral-800 
              shadow 
              overflow-hidden">
              <div className="p-6 sm:p-8">
                <Header></Header>
                <div className="      
                w-full max-w-6xl 
                bg-white dark:bg-neutral-950 
                border border-neutral-200 dark:border-neutral-800 
                shadow 
                overflow-hidden">
                  {children}
                </div>
              </div>
            </div>
          </div>  
          </ThemeProvider>
      </body>
    </html>
  );
}
